#!bin/bash


# error precaution.
set -e
# default unzip folder.
DIR='app/main'
mkdir -p "$DIR"

# get zip file from variable.
ZIP_LINK="${ZIP_LINK:-"echo put_your_link_in_variables"}"

_startbot () {
    cd $DIR/*
    sleep 3
    echo "  --- >><< --- Starting [X] --- >><< ---"
    bash run
    sleep 5
}


_setup_repo () {
    local zippath
    zippath="app/myleech.zip"
    echo "  Fetching update from Upstream Repo..."
    wget -q "$ZIP_LINK" -O "$zippath"
    echo "  Unpacking Data ..."
    unzip -qq "$zippath" -d "$DIR"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"  
    sleep 5
    _startbot
}


_setup_repo
