#!bin/bash


# error precaution.
set -e
# default unzip folder.
DIR='app/main'
mkdir -p "$DIR"

_get_ziplink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO =~ $regex ]]
    then 
        echo "https://github.com/Sanjeev20012000/prgone/archive/refs/heads/old-pyro.zip"
    else
        echo "https://github.com/gautamajay52/TorrentLeech-Gdrive/archive/refs/heads/master.zip"
    fi
}

_startbot () {
    cd $DIR/*
    sleep 3
    echo "  --- >><< --- Starting [X] --- >><< ---"
    bash start.sh
    sleep 5
}


_setup_repo () {
    local zippath
    zippath="app/master.zip"
    wget -q "https://github.com/Sanjeev20012000/prgone/archive/refs/heads/old-pyro.zip" -O "$zippath"
    echo "  Unpacking Data ..."
    unzip -qq "$zippath" -d "$DIR"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"  
    sleep 5
    _startbot
}


_setup_repo
